/**
 * Created by maoyuyang on 17/8/27.
 */

// auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const USERINFO_SUCCESS = 'USERINFO_SUCCESS'
export const LOGOUT_USER = 'LOGOUT_USER'
export const USERINFO_FAILURE = 'USERINFO_FAILURE'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER = 'UPDATE_USER'
export const ADD_USER_LIKES = 'ADD_USER_LIKES'
export const DEL_USER_LIKES = 'DEL_USER_LIKES'

// showmsg, showdialog
export const SHOW_MSG = 'SHOW_MSG'
export const SHOW_LOGIN_DIALOG = 'SHOW_LOGIN_DIALOG'
export const HIDE_LOGIN_DIALOG = 'HIDE_LOGIN_DIALOG'
export const SHOW_REGISTER_DIALOG = 'SHOW_REGISTER_DIALOG'
export const HIDE_REGISTER_DIALOG = 'HIDE_REGISTER_DIALOG'
export const SHOW_PUBLISH_DIALOG = 'SHOW_PUBLISH_DIALOG'
export const HIDE_PUBLISH_DIALOG = 'HIDE_PUBLISH_DIALOG'
export const HIDE_CONVER_DIALOG = 'HIDE_CONVER_DIALOG'
export const SHOW_CONVER_DIALOG = 'SHOW_CONVER_DIALOG'

// article
export const ARTICLE_LIST = 'ARTICLE_LIST'
export const ADD_ARTICLE = 'ADD_ARTICLE'
export const ADD_ARTICLE_FAILURE = 'ADD_ARTICLE_FAILURE'
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS'
export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST'
export const GET_ARTICLE_LIST_FAILURE = 'GET_ARTICLE_LIST_FAILURE'
export const ARTICLE_DETAIL = 'ARTICLE_DETAIL'
export const ARTICLE_DETAIL_FAILURE = 'ARTICLE_DETAIL_FAILURE'
export const TOGGLE_LIKE = 'TOGGLE_LIKE'
export const ARTICLE_PRENEXT = 'ARTICLE_PRENEXT'
export const COMMENT_LIST = 'COMMENT_LIST'
export const SUCCESS_ADD_COMMENT = 'SUCCESS_ADD_COMMENT'
export const SUCCESS_ADD_REPLAY = 'SUCCESS_ADD_REPLAY'
export const GET_COMMENT_LIST_FAILURE = 'GET_COMMENT_LIST_FAILURE'

// comment
export const GET_CONVERSATION = 'GET_CONVERSATION'
export const GET_CONVERSATION_SUCCESS = 'GET_CONVERSATION_SUCCESS'

// options
export const CHANGE_OPTIONS = 'CHANGE_OPTIONS'
